### ISSUE TITLE
Error in UseMethod("tidy_stats") :    no applicable method for 'tidy_stats' applied to an object of class "c('summary_emm', 'data.frame')"

### ISSUE THREAD

**Issue by Scott-S-Hannah** [WillemSleegers/tidystats#11]
Hi Willem, 

Have been making good use of the `tidystats` package lately and came across an issue when combining families of comparisons via `emmeans::test()`. This would be a nice addition to allow for correct multiplicity adjustments. 

```
library(afex)
library(tidystats)

participant <- rep(seq(1, 10), each = 21)
condition <- rep(c("cond_1", "cond_2", "cond_3"), times = 70)
time <- rep(seq(0, 30, 5), each = 3, times = 10)
response <- rnorm(n = 210, mean = c(1.1, 1.2, 1.3), sd = 0.1)

df <- data.frame(participant = factor(participant),
                 time = factor(time),
                 condition = factor(condition),
                 response)

model <- mixed(response ~ condition * time +
                 (condition | participant),
               df)

emm_results <- emmeans(model, "condition", by = "time") %>% 
  contrast("trt.vs.ctrl") %>%
  test(by = NULL)

results <- list()

results <- results %>% 
  add_stats(emm_results)
```

Thanks again,
Scott

**Comment by WillemSleegers** [comment]
Hey @Scott-S-Hannah, thanks again for creating an issue, and sorry it took me a while to see it!

I pushed some code to the dev version of `tidystats`, so you should be able to tidystats your `emm_results` variable now. The reason it didn't work before is because `test()` returns a different type of object (with class `summary_emm`) and I simply hadn't added support for that yet. I added some now, although so far it will only work if you have 1 grouping variable (like in your case).

Let me know if you run into any bugs!

**Comment by Scott-S-Hannah** [comment]
Working a treat so far @WillemSleegers. Thanks again 👍🏻.
